### ISSUE TITLE
[Bug]: The Trino parser seems to be broken

### ISSUE THREAD

**Issue by s-ajith-kumar** [DTStack/dt-sql-parser#266]
### Version

4.0.0-beta.4.11

### Which SQL?

Trino

### SQL content

```sql
select * from whatever limit 100;
```

### What happened?

The Trino parser doesn't seem to be working for the limit query mentioned above. 100 is being excluded by the parser

For "select * from whatever limit 100;", the parser (**splitSQLByStatement**) returns "select * from whatever limit"

**Comment by LuckyFBB** [comment]
I tried to reproduce the issue locally and found no problem. 
Just because there are too many parsed nodes, 100 has not been displayed on the screen. You can see the node by scrolling the current screen.
Please check this gif.
![1](https://github.com/DTStack/dt-sql-parser/assets/38368040/2fe99f73-a628-41fa-a7a2-65e2c1201ca6)

**Comment by s-ajith-kumar** [comment]
Opening this again. The issue is actually with **splitSQLByStatement**

![image](https://github.com/DTStack/dt-sql-parser/assets/84699656/181dde51-9524-4e1a-b819-d82c8e24ddba)

**Comment by LuckyFBB** [comment]
version: 4.0.0-beta.4.11
<img width="410" alt="图片" src="https://github.com/DTStack/dt-sql-parser/assets/38368040/6cfdab76-f30b-43e1-bfed-897d12b57edb">

verison: 4.0.1
<img width="446" alt="图片" src="https://github.com/DTStack/dt-sql-parser/assets/38368040/8ca63007-db74-4322-8105-c3d558a2a7cd">

yes, this is a bug for version 4.0.0-beta.4.11, and we resolve it at lastest version 4.0.1, please upgrade your sql-parser version

**Comment by HaydenOrz** [comment]
Close because inactive
